### PR TITLE
Create chisq rmd brief tutorial within cheatsheets

### PR DESCRIPTION
**Pull request by sgagnon**

### CODE REVIEW

**Comment by hawkrobe** [comment]
Would it also be worth mentioning in a footnote that in practice a non-parametric permutation test can always replace a chi-squared test, and since the permutation test is both simpler and more accurate for small sample sizes, you don't actually see the chi-squared test used that much in the literature anymore?

**Comment by sgagnon** [comment]
It might be worth putting that in a footnote, though I think only a small
portion of the class will understand what that means!

On Tue, Sep 15, 2015 at 6:13 PM, Robert X.D. Hawkins <
notifications@github.com> wrote:

> Would it also be worth mentioning in a footnote that in practice a
> non-parametric permutation test can always replace a chi-squared test, and
> since the permutation test is both simpler and more accurate for small
> sample sizes, you don't actually see the chi-squared test used that much in
> the literature anymore?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ewartthomas/Psych252/pull/1#issuecomment-140591978.

## 

Ph.D. Student
Stanford Memory Laboratory
Department of Psychology
Stanford University

**Comment by kgweisman** [comment]
I second Steph - also, they're pretty common in the developmental
literature! (For better or worse?)

---

Kara Weisman
Ph.D. Student
Department of Psychology
Stanford University

**Comment by hawkrobe** [comment]
Maybe we can chat about the larger teaching philosophy in our meeting tomorrow, but I've always appreciated it when instructors drop breadcrumbs of more advanced stuff that interested students can follow-up on! We do discuss the bootstrap later in the term, and permutation tests are motivated by the same reasoning. 

I also remember the question -- "when is it inappropriate to use a chi-squared" -- coming up naturally in section last year. It's pretty common when you have a big (observational) contingency table to have at least one cell with no counts, or (in experimental designs) a number of cells with less than 5 counts. For those cases the chi-squared approximation doesn't hold, and you should use a permutation test (or I guess Fisher's exact test) I figure that the handout is "bonus content," so that a little discussion of these issues might be appropriate!

**Comment by ewartthomas** [comment]
colleagues, a number of issues invite comment.
1. on the ‘height-salary’ example, i wd prefer to replace the existing data set with one in which ‘height’ is replaced by ‘years’ (of relevant experience), because it’s more satisfying to have students thinking about a ‘serious’ issue (e.g., are compensation schemes ‘rational’) than a ‘playful’ issue (e.g., why height shd be correl with $$).  i suggested the transform so as to get realistic numbers for ‘years’, but that step will be hidden from view in the 2nd iteration of the fake data set.
2. let us agree to spend time tomorrow chatting about teaching philosophy - but our views on this issue are orthogonal to the design of the r tutorial syllabus.  as i said earlier, thru the tutorial we are trying to get rid of the excessive anxiety we used to see in the 1st 2 weeks of the course.  i’m not trying to design the ‘best’ intro to stats or to r.  so i don’t want us to feel badly about not explaining how t is defined, or why chisq is a large sample test; or about not giving the purist’s intro to object-oriented programming.  this is why i wd see ‘perm tests’ as a possible topic for the course, but not for fri’s tutorial.  but each of us shd feel free to ad lib ...
3. a non-trivial part of becoming a good researcher is learning how to pose an answerable question, and how to organise the data to get an answer.  as i said earlier, my ideal question at this level is, ‘here’s a data set and here’s the definition of the variables.  do a few ‘interesting’ analyses of the data.’  for a lot of reasons, this wd be unfair to the stats neophyte, so we spend most of the qtr with ‘do an lm()’ type exercises, and we teach the relevant techniques.  but i hope that we can use 1 or 2 occasions on fri to get students to think about the ‘interesting’ substantive issues underlying the data set.

see you soon.
e

On Sep 15, 2015, at 6:40 PM, Robert X.D. Hawkins <notifications@github.com<mailto:notifications@github.com>> wrote:

Maybe we can chat about the larger teaching philosophy in our meeting tomorrow, but I've always appreciated it when instructors drop breadcrumbs of more advanced stuff that interested students can follow-up on! We do discuss the bootstrap later in the term, and permutation tests are motivated by the same reasoning.

I also remember the question -- "when is it inappropriate to use a chi-squared" -- coming up naturally in section last year. It's pretty common when you have a big (observational) contingency table to have at least one cell with no counts, or (in experimental designs) a number of cells with less than 5 counts. For those cases the chi-squared approximation doesn't hold, and you should use a permutation test (or I guess Fisher's exact test) I figure that the handout is "bonus content," so that a little discussion of these issues might be appropriate!

**Pull request merged**
